source 'https://rubygems.org'

gem 'bundler'
gem 'rspec-rails'
gem 'capybara'
gem 'poltergeist'
gem 'selenium-webdriver'
gem 'capybara-screenshot'
gem 'factory_girl'
gem 'activesupport'
gem 'chromedriver-helper'
gem 'faker'
gem 'byebug'
gem 'ruby-smpp', git: 'https://github.com/raykrueger/ruby-smpp'
# gem "iconv", "~> 1.0.3"
